spring:
  application:
    name: procoop-backend

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:${WEB_RESOURCES_STATIC-LOCATIONS}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}

app:
  uploads:
    dir: ${APP_UPLOADS_DIR}
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}
  frontend:
    url: ${APP_FRONTEND_URL}
  openai:
    api-key: ${APP_OPENAI_API_KEY}
    url: ${APP_OPENAI_URL}
    model: ${APP_OPENAI_MODEL}
  cloudinary:
      cloud-name: ${APP_CLOUDINARY_CLOUD_NAME}
      api-key: ${APP_CLOUDINARY_API_KEY}
      api-secret: ${APP_CLOUDINARY_API_SECRET}
logging:
  level:
    ar.edu.undec.procoop: INFO
